Repository Dongmanee/frontend, pull requests merged in 2023-11, with the labels that each got.

#1 test
  src/styles/theme.js
Labels: ✅TEST

#5 test: 테스트
  src/App.js
Labels: ✨FEAT

#7 feat: 동아리 홈
  src/components/club/ClubInfo.js
  src/components/club/ClubJoinButton.js
  src/components/club/ClubPost.js
  src/components/club/Clubpage.js
  src/components/global/CustomButton.js
  src/components/global/Header.js
  src/components/global/Navbar.js
  src/components/global/PageSelector.js
  src/components/global/post/Post.js
  src/images/sample.png
  src/layouts/HomeLayout.js
  src/layouts/Layout.js
  src/pages/ClubHome.js
  src/pages/Home.js
  src/pages/Login.js
  src/router/router.js
  src/styles/global.style.js
  src/styles/theme.js
Labels: ✨FEAT

#9 feat: 홈 - 전체 게시글, 홈 - 전체 동아리
  public/index.html
  src/components/club/ClubPost.js
  src/components/global/CustomInputs.js
  src/components/global/Header.js
  src/components/global/Navbar.js
  src/components/global/ProfileAndName.js
  src/components/global/post/Post.js
  src/components/global/postList/Post.js
  src/components/global/postList/PostBody.js
  src/components/global/postList/PostHead.js
  src/components/global/postList/PostReactionNum.js
  src/components/global/postList/PostWriter.js
  src/components/global/register/RegisterInput.js
  src/components/global/register/RegisterLabel.js
  src/components/home/HomeClubList.js
  src/components/home/clubs/ClubCard.js
  src/components/home/clubs/ClubCardHeadInfo.js
  src/components/home/clubs/ClubCategoryList.js
  src/components/home/clubs/ClubList.js
  src/components/home/clubs/RegisterClubCategory.js
  src/consts/tempData.js
  src/images/club-category/computer.png
  src/images/club-category/total.png
  src/layouts/Layout.js
  src/pages/Home.js
  src/pages/HomeTotalClubs.js
  src/pages/RegisterClub.js
  src/router/router.js
  src/styles/global.style.js
  src/styles/theme.js
Labels: ✨FEAT

#11 feat: 전체 동아리
  package-lock.json
  package.json
  src/components/global/CustomInputs.js
  src/components/global/HorizontalSlider.js
  src/components/global/register/RegisterButton.js
  src/components/global/register/RegisterErrorMsg.js
  src/components/global/register/RegisterImage.js
  src/components/global/register/RegisterInput.js
  src/components/global/register/RegisterLabel.js
  src/components/global/register/RegisterTag.js
  src/components/home/clubs/ClubList.js
  src/components/home/clubs/RegisterClubCategory.js
  src/pages/Clubs.js
  src/pages/Posts.js
  src/pages/RegisterClub.js
  src/router/router.js
Labels: ✨FEAT

#14 feat: 로그인, 회원가입 UI
  src/components/auth/OtherApproach.js
  src/components/auth/login/KakaoLogin.js
  src/components/auth/login/LoginForm.js
  src/components/auth/signup/SignupForm.js
  src/components/global/CustomButton.js
  src/components/global/register/RegisterButton.js
  src/components/global/register/RegisterInput.js
  src/pages/Home.js
  src/pages/Login.js
  src/pages/RegisterClub.js
  src/pages/Signup.js
  src/router/router.js
Labels: ✨FEAT

#15 feat : 동아리 관리 페이지 UI
  src/components/clubSetting/applications/ApplicationCard.js
  src/components/clubSetting/applications/ApplicationCardInfo.js
  src/components/clubSetting/inquiries/ConfirmStateBox.js
  src/components/clubSetting/inquiries/InquiryCard.js
  src/components/clubSetting/inquiries/InquiryCardInfo.js
  src/components/clubSetting/members/ClubRoleState.js
  src/components/clubSetting/members/MemberCard.js
  src/components/clubSetting/members/MemberCardInfo.js
  src/components/clubSetting/members/ResignButton.js
  src/consts/tempData.js
  src/pages/HomeTotalClubs.js
  src/pages/club/ClubHome.js
  src/pages/clubSetting/ClubSetting.js
  src/pages/clubSetting/ClubSettingApplications.js
  src/pages/clubSetting/ClubSettingInquiries.js
  src/pages/clubSetting/ClubSettingMembers.js
  src/router/router.js
Labels: ✨FEAT

#18 feat: 동아리홈 게시판 글 쓰기 / 수정 / 일정 추가
  src/components/global/Header.js
  src/components/global/register/RegisterInput.js
  src/consts/tempData.js
  src/pages/club/ClubPosts.js
  src/pages/club/ClubPostsEdit.js
  src/pages/club/ClubScheduleAdd.js
  src/router/router.js
Labels: ✨FEAT

#21 feat: 동아리홈 기능 구현
  src/components/club/ClubUser.js
  src/components/club/ClubUserList.js
  src/components/club/Clubpage.js
  src/components/club/posts/ClubPost.js
  src/components/club/posts/ClubPostsCategory.js
  src/components/club/schedule/AddButton.js
  src/components/club/schedule/ClubScheduleInfo.js
  src/components/club/schedule/ClubScheduleItem.js
  src/components/club/schedule/ClubScheduleItemContent.js
  src/components/global/Header.js
  src/components/global/PageSelector.js
  src/components/global/PenIcon.js
  src/components/global/SmallTagBox.js
  src/consts/tempData.js
  src/hooks/useCheckPath.js
  src/pages/club/Club.js
  src/pages/club/ClubAlbum.js
  src/pages/club/ClubHome.js
  src/pages/club/ClubPosts.js
  src/pages/club/ClubPostsEdit.js
  src/pages/club/ClubSchedule.js
  src/pages/club/ClubScheduleDetail.js
  src/router/router.js
Labels: ✨FEAT

#22 feat: 동아리 관리 상세 페이지 UI, 동아리 멤버관리 수정
  src/components/clubSetting/inquiries/ConfirmStateBox.js
  src/components/clubSetting/inquiries/InquiryDetailItem.js
  src/components/clubSetting/members/ClubRoleDropDown.js
  src/components/clubSetting/members/ClubRoleState.js
  src/components/clubSetting/members/MemberCard.js
  src/components/clubSetting/members/MemberCardInfo.js
  src/components/clubSetting/members/ResignButton.js
  src/components/clubSetting/members/ResignModal.js
  src/components/global/Header.js
  src/pages/clubSetting/ClubSetting.js
  src/pages/clubSetting/ClubSettingApplicationDetail.js
  src/pages/clubSetting/ClubSettingInquiryDetail.js
  src/router/router.js
Labels: ✨FEAT

#24 feat: 이전 페이지 기능 구현
  src/components/auth/login/KakaoLogin.js
  src/components/global/Header.js
  src/hooks/usePrevPage.js
  src/layouts/Layout.js
  src/pages/Login.js
  src/pages/club/Club.js
  src/pages/club/ClubPostsDetail.js
  src/pages/user/User.js
Labels: ✨FEAT

#26 feat: 회원가입 페이지 UI 구현
  src/components/auth/signup/AuthEmailModal.js
  src/components/auth/signup/RegisterEmailInput.js
  src/components/auth/signup/SignupForm.js
  src/components/club/ClubUserProfile.js
  src/components/clubSetting/members/ResignModal.js
  src/components/global/CustomButton.js
  src/components/global/register/RegisterInput.js
  src/components/global/register/RegisterLabel.js
  src/layouts/ModalLayout.js
  src/pages/Signup.js
Labels: ✨FEAT

#28 feat: 회원가입 기능 구현
  package-lock.json
  package.json
  src/apis/signup.js
  src/components/auth/signup/AuthEmailModal.js
  src/components/auth/signup/RegisterEmailInput.js
  src/components/auth/signup/SignupForm.js
  src/components/global/CustomInputs.js
  src/components/global/register/RegisterErrorMsg.js
  src/components/global/register/RegisterInput.js
  src/components/global/register/RegisterLabel.js
  src/layouts/ModalLayout.js
  src/pages/Signup.js
  src/utils/validationSchema.js
Labels: ✨FEAT

#32 feat: 로그인 기능 구현
  package-lock.json
  package.json
  src/apis/login.js
  src/apis/signup.js
  src/components/auth/login/KakaoLogin.js
  src/components/auth/login/LoginForm.js
  src/components/auth/signup/RegisterEmailInput.js
  src/components/auth/signup/SignupForm.js
  src/components/global/CustomButton.js
  src/components/global/CustomInputs.js
  src/components/global/register/RegisterErrorMsg.js
  src/components/global/register/RegisterInput.js
  src/index.js
  src/pages/club/Club.js
  src/pages/club/ClubPostsEdit.js
  src/router/router.js
  src/utils/validationSchema.js
Labels: ✨FEAT

#33 feat: 홈 기능 일부 추가 및 변경
  src/apis/signup.js
  src/components/global/CategoryIcon.js
  src/components/global/CustomInputs.js
  src/components/global/ProfileAndName.js
  src/components/global/postList/Post.js
  src/components/global/postList/PostBody.js
  src/components/global/register/RegisterImage.js
  src/components/global/register/RegisterTag.js
  src/components/global/register/RegisterTextArea.js
  src/components/home/HomeClubList.js
  src/components/home/clubRegister/RegisterClubCategory.js
  src/components/home/clubs/ClubCard.js
  src/components/home/clubs/ClubCategoryList.js
  src/consts/tempData.js
  src/images/club-category/angel.png
  src/images/club-category/festival.png
  src/images/club-category/heart.png
  src/images/club-category/museum.png
  src/images/club-category/sports.png
  src/pages/Clubs.js
  src/pages/Posts.js
  src/pages/RegisterClub.js
Labels: ✨FEAT, 🛠️FIX
